export enum UserRole {
  SAAS_ADMIN = 'SAAS_ADMIN',
  SAAS_EDITOR = 'SAAS_EDITOR',
  OWNER = 'OWNER',
  SUPERVISOR = 'SUPERVISOR',
  MERCHANT_USER = 'MERCHANT_USER',
  LOGISTICS_PROVIDER = 'LOGISTICS_PROVIDER',
  DRIVER = 'DRIVER',
  CUSTOMER = 'CUSTOMER',
}

